config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :websites, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
  has_one_attached :full_website
  has_one_attached :mobile_website

  validates :full_website, presence: true
  validates :mobile_website, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, ]

  def home
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @websites = Website.all
  end

  def new
    @website = Website.new
  end

  def create
    @website = Website.new(website_params)
    if @website.save
      redirect_to websites_path
    else
      render :new
    end
  end

  def edit
    @website = Website.find(params[:id])
  end

  def update
    @website = Website.find(params[:id])
    @website.update_attributes(website_params)
    @website.save
    redirect_to websites_path
  end

  def destroy
    @website = Website.find(params[:id])
    @website.destroy
    redirect_to websites_path
  end

  private

  def website_params
    params.require(:website).permit(
      :name,
      :full_website,
      :mobile_website,
      :description,
      :web_link,
      :github_link,
      :code_tags,
      :live,
      :favourite
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KarlPortfolioPage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="my-banner">
  <h1 class="name">
    Karl Loomes
  </h1>
  <div class="button-container">
    <%= link_to "Portfolio", websites_path, class: "my-button" %>
    <a class="my-button" href="#about">
      About
    </a>
    <a class="my-button" href="#contact">
      Contact
    </a>
  </div>
  <div class="my-avatar">

  </div>
</div>
<div class="favourite-container">
  <div class="laptop-image">
    Laptop
  </div>
  <div class="mobile-image">
    Mobile
  </div>
</div>
<div class="about-me" id="about">
  <h3>About</h3>
  <p>My name is Karl and I am a full stack web developer.</p>
</div>
<div class="contact-bar" id="contact">
  <a href="https://www.linkedin.com/in/karl-loomes" target="_blank">
    <i class="fab fa-linkedin"></i>
  </a>
  <a href="https://github.com/kloomes" target="_blank">
    <i class="fab fa-github-square"></i>
  </a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/websites/edit.html.erb
<h1>Edit Website</h1>
<%= simple_form_for @website do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :web_link %>
  <%= f.input :github_link %>
  <%= f.input :code_tags %>
  <%= f.input :live %>
  <%= f.input :favourite %>
  <%= f.input :full_website, as: :file %>
  <%= f.input :mobile_website, as: :file %>
  <%= f.submit %>
<% end %>
<%= link_to 'Delete', website_path(params[:id]), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/websites/index.html.erb
<h1>Portfolio Page</h1>
<% @websites.each do |website| %>
  <p><%= website.name %></p>
  <p><%= website.description %></p>
  <p><%= website.web_link %></p>
  <p><%= website.github_link %></p>
  <p><%= website.code_tags %></p>
  <p><%= website.live %></p>
  <p><%= website.favourite %></p>
  <%= cl_image_tag website.full_website.key, height: 300, width: 400, crop: :fill %>
  <%= cl_image_tag website.mobile_website.key, height: 300, width: 200, crop: :fill %>
<% end %>

app/views/websites/new.html.erb
<h1>Add Website</h1>
<%= simple_form_for @website do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :web_link %>
  <%= f.input :github_link %>
  <%= f.input :code_tags %>
  <%= f.input :live %>
  <%= f.input :favourite %>
  <%= f.input :full_website, as: :file %>
  <%= f.input :mobile_website, as: :file %>
  <%= f.submit %>
<% end %>